### ISSUE TITLE
Cuda error with 3090

### ISSUE THREAD

**Issue by HandsomeDevilv112** [msieg/deep-visualizer#28]
I can run the test just fine until it comes time for the rubber to hit the road.
Is anybody else experiencing this? and/or, how did you fix it?

```
Reading audio 


Generating input vectors 

100%|█████████████████████████████████████| 2586/2586 [00:01<00:00, 2400.27it/s]


Generating frames 

  0%|                                                    | 0/86 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/al/deep-music-visualizer/visualize.py", line 378, in <module>
    output = model(noise_vector, class_vector, truncation)
  File "/home/al/anaconda3/envs/ddvisualizer/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/al/anaconda3/envs/ddvisualizer/lib/python3.9/site-packages/pytorch_pretrained_biggan/model.py", line 293, in forward
    cond_vector = torch.cat((z, embed), dim=1)
RuntimeError: CUDA error: no kernel image is available for execution on the device
`
```

**Comment by HandsomeDevilv112** [comment]
Reinstalled the cuda toolkit in the environment did the trick. Closing. 

conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
